# Example configuration file for a Web::DataService application using
# Dancer as the foundation framework.

# These settings are read by Web::DataService

title: "Web::DataService Example"
data_source: "U.S. Bureau of the Census"
data_file: "data/population_data.txt"
contact_name: "J. A. Perlhacker"
contact_email: "japh@example.com"

# Settings may be placed under the data service name, as well as at
# the top level.

data1.0:
    default_limit: 500

# These settings are read by Dancer

port: 3000
charset: "UTF-8"
environment: "production"

# If you wish to access a backend datastore via DBI, you can uncomment the following and substitute the
# appropriate settings.  You will need to make sure that your main application requires the module
# Dancer::Plugin::Database.  Then, you can use the method 'get_connection' to retrieve a database handle
# whenever you need one.

# plugins:
#     Database:
#       driver: 'mysql'
#       database: 'my_database'
#       host: 'localhost:mysql_socket=my_socket_path'
#       username: 'my_username'
#       password: 'my_password'

